//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountNumber { get; set; }
        public string SolId { get; set; }
        public Nullable<System.DateTime> AsAtDate { get; set; }
        public string Name { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> GrantedAmountLKR { get; set; }
        public Nullable<decimal> CapitalLKR { get; set; }
        public Nullable<decimal> InterestOSLKR { get; set; }
        public Nullable<System.DateTime> GrantedDate { get; set; }
        public string Currency { get; set; }
        public string ImpairmentStatus { get; set; }
        public Nullable<decimal> ImpairmentAmount { get; set; }
        public Nullable<decimal> PresentValue { get; set; }
        public string Classification { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<decimal> AmortizedAmount { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> AppliedInterestRate { get; set; }
        public Nullable<decimal> TotalCashFlowAmount { get; set; }
        public string DelFlag { get; set; }
        public string CustomerId { get; set; }
        public string FreeText_1 { get; set; }
        public string FreeText_2 { get; set; }
        public string FreeText_3 { get; set; }
        public Nullable<System.DateTime> FreeDate_1 { get; set; }
        public Nullable<System.DateTime> FreeDate_2 { get; set; }
        public Nullable<decimal> FreeNo_1 { get; set; }
        public Nullable<decimal> FreeNo_2 { get; set; }
        public string RcReUser { get; set; }
        public Nullable<System.DateTime> RcReTime { get; set; }
        public string LchgUser { get; set; }
        public Nullable<System.DateTime> LchgTime { get; set; }
        public Nullable<decimal> Currency_Rate { get; set; }
    }
}
