//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow
    {
        public decimal Id { get; set; }
        public string CustomerId { get; set; }
        public string AccountNumber { get; set; }
        public string SolId { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PresentValue { get; set; }
        public string Status { get; set; }
        public string EntryUserId { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> AsAtDate { get; set; }
        public string DelFlag { get; set; }
        public string FreeText_1 { get; set; }
        public string FreeText_2 { get; set; }
        public string FreeText_3 { get; set; }
        public Nullable<System.DateTime> FreeDate_1 { get; set; }
        public Nullable<System.DateTime> FreeDate_2 { get; set; }
        public Nullable<decimal> FreeNo_1 { get; set; }
        public Nullable<decimal> FreeNo_2 { get; set; }
        public string RcReUser { get; set; }
        public Nullable<System.DateTime> RcReTime { get; set; }
        public string LchgUser { get; set; }
        public Nullable<System.DateTime> LchgTime { get; set; }
    }
}
