//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string BranchId { get; set; }
        public string BranchCode { get; set; }
        public string BrancType { get; set; }
        public Nullable<decimal> CapitalOSLKR { get; set; }
        public string StatusCode { get; set; }
        public Nullable<decimal> TotalPresentValue { get; set; }
        public Nullable<decimal> TotalAmortizedAmount { get; set; }
        public Nullable<decimal> TotalCashFlowsAmount { get; set; }
        public Nullable<decimal> TotalImpairmentAmount { get; set; }
        public string ImpairmentStatus { get; set; }
        public string EntryUserId { get; set; }
        public Nullable<System.DateTime> AsAtDate { get; set; }
        public string DelFlag { get; set; }
        public string RelationshipManager { get; set; }
        public string Verify_1 { get; set; }
        public string Verify_2 { get; set; }
        public string Verify_3 { get; set; }
        public string Verify_4 { get; set; }
        public string q1 { get; set; }
        public string q2 { get; set; }
        public string q3 { get; set; }
        public string q4 { get; set; }
        public string q5 { get; set; }
        public string q6 { get; set; }
        public string q7 { get; set; }
        public string q8 { get; set; }
        public string q9 { get; set; }
        public string q10 { get; set; }
        public string q11 { get; set; }
        public string q12 { get; set; }
        public string q13 { get; set; }
        public string q14 { get; set; }
        public string q15 { get; set; }
        public string q16 { get; set; }
        public string q17 { get; set; }
        public string q18 { get; set; }
        public string q19 { get; set; }
        public string q20 { get; set; }
        public string q21 { get; set; }
        public string q22 { get; set; }
        public string q23 { get; set; }
        public string q24 { get; set; }
        public string q25 { get; set; }
        public string q26 { get; set; }
        public string q27 { get; set; }
        public string q28 { get; set; }
        public string q29 { get; set; }
        public string q30 { get; set; }
        public string StatusHistory { get; set; }
        public string FreeText_1 { get; set; }
        public string FreeText_2 { get; set; }
        public string FreeText_3 { get; set; }
        public Nullable<System.DateTime> FreeDate_1 { get; set; }
        public Nullable<System.DateTime> FreeDate_2 { get; set; }
        public Nullable<decimal> FreeNo_1 { get; set; }
        public Nullable<decimal> FreeNo_2 { get; set; }
        public string RcReUser { get; set; }
        public Nullable<System.DateTime> RcReTime { get; set; }
        public string VerifiedUser { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
        public string LchgUser { get; set; }
        public Nullable<System.DateTime> LchgTime { get; set; }
        public string Npa_Pa { get; set; }
        public string Mora_Status { get; set; }
        public string Customer_Type { get; set; }
        public string AnswerRemark { get; set; }
    }
}
