//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> AsAtDate { get; set; }
        public string CustomerId { get; set; }
        public string Remarks { get; set; }
        public string DelFlag { get; set; }
        public string RcReUser { get; set; }
        public Nullable<System.DateTime> RcReTime { get; set; }
        public string LchgUser { get; set; }
        public Nullable<System.DateTime> LchgTime { get; set; }
    }
}
