//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string NameWithInitials { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string ReportingId { get; set; }
    }
}
